In [1]:

# coding: utf-8

import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import sklearn.linear_model



In [3]:
def plot_decision_boundary(model, X, y):
    # Set min and max values and give it some padding
    x_min, x_max = X[0, :].min() - 1, X[0, :].max() + 1
    y_min, y_max = X[1, :].min() - 1, X[1, :].max() + 1
    h = 0.01
    # Generate a grid of points with distance h between them
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    # Predict the function value for the whole grid
    Z = model(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    # Plot the contour and training examples
    plt.contourf(xx, yy, Z, cmap=plt.cm.Spectral)
    plt.ylabel('x2')
    plt.xlabel('x1')
    plt.scatter(X[0, :], X[1, :], c=y.ravel(), cmap=plt.cm.Spectral)

In [16]:

def load_planar_dataset():
    np.random.seed(1)
    m = 400 # number of examples
    N = int(m/2) # number of points per class
    D = 2 # dimensionality
    X = np.zeros((m,D)) # data matrix where each row is a single example
    Y = np.zeros((m,1), dtype='uint8') # labels vector (0 for red, 1 for blue)
    #print("x,y shape" , X.shape , Y.shape)
    a = 4 # maximum ray of the flower

    for j in range(2):
        ix = range(N*j,N*(j+1))
        print("ix shape" , ix)
        t = np.linspace(j*3.12,(j+1)*3.12,N) + np.random.randn(N)*0.2 # theta
        print("t shape" ,t.shape)
        r = a*np.sin(4*t) + np.random.randn(N)*0.2 # radius
        X[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
        Y[ix] = j
        
    X = X.T
    Y = Y.T

    return X, Y


In [35]:
# explaniation of above load_datasts process


m=20
d =2
N =10
a=4
X = np.zeros((m,d))
Y = np.zeros((m,1))
for j in range(2):
    ix = range(N*j,N*(j+1))
    print("ix shape" , ix)
    t = np.linspace(j*3.12,(j+1)*3.12,N) + np.random.randn(N)*0.2 # theta
    #t =  np.linspace(j*3.12,(j+1)*3.12,N)
    print("t shape" ,t.shape)
    r = a*np.sin(4*t) + np.random.randn(N)*0.2 # radius
    sa = r*np.sin(t), r*np.cos(t)
    #print(sa)
    print(np.c_[[3,4], [2,3]])
    X[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
    Y[ix] = j
    print(X.shape ,Y.shape)    

ix shape range(0, 10)
t shape (10,)
[[3 2]
 [4 3]]
(20, 2) (20, 1)
ix shape range(10, 20)
t shape (10,)
[[3 2]
 [4 3]]
(20, 2) (20, 1)


In [36]:
zz =load_planar_dataset()

zz

ix shape range(0, 200)
t shape (200,)
ix shape range(200, 400)
t shape (200,)


(array([[ 1.20444229e+00,  1.58709904e-01,  9.52471960e-02,
          3.49178475e-01,  6.94150378e-01,  1.62065038e+00,
          1.53856225e+00,  3.63085641e-02,  4.74591109e-01,
          1.65695828e-01,  1.66446249e+00,  8.40285720e-01,
          2.61695163e-01,  2.31614896e-01,  1.58013020e+00,
          6.35509950e-03,  6.80610419e-01,  1.21400432e-01,
          1.13281261e+00,  1.61505892e+00,  1.66454441e-01,
          1.72438241e+00,  1.88667246e+00,  1.72327227e+00,
          1.54661332e+00,  9.84590400e-01,  1.45313345e+00,
          7.49043388e-01,  1.45048341e+00,  1.64287865e+00,
          1.28141487e+00,  1.59574104e+00,  1.46298294e+00,
          1.46629048e+00,  1.54348961e+00,  1.57013416e+00,
          1.22995404e+00,  1.31142345e+00, -1.99364553e+00,
          3.94564752e-01,  1.51715449e+00,  1.69169139e+00,
          1.74186686e+00, -2.91373382e+00,  7.52150898e-01,
          1.68537303e+00,  3.71160238e-01, -3.73033884e+00,
          3.52484080e-01, -1.48694206e+0

In [53]:

def load_extra_datasets():  
    N = 200
    noisy_circles = sklearn.datasets.make_circles(n_samples=N, factor=.5, noise=.3)
    #print(noisy_circles)
    noisy_moons = sklearn.datasets.make_moons(n_samples=N, noise=.2)
    blobs = sklearn.datasets.make_blobs(n_samples=N, random_state=5, n_features=2, centers=6)
    gaussian_quantiles = sklearn.datasets.make_gaussian_quantiles(mean=None, cov=0.5, n_samples=N, n_features=2, n_classes=2, shuffle=True, random_state=None)
    no_structure = np.random.rand(N, 2), np.random.rand(N, 2)
    
    return noisy_circles, noisy_moons, blobs, gaussian_quantiles, no_structure



In [59]:
zx = load_extra_datasets()
zx[0][:1]

(array([[-2.27114817e-01, -3.09445721e-03],
        [-9.16993016e-01,  1.16697887e-01],
        [-2.16376092e-01, -9.22740734e-01],
        [-9.95659803e-01, -2.06904398e-01],
        [ 5.44149447e-01, -6.35701965e-01],
        [-2.26092055e-01, -4.37635124e-01],
        [-2.60446930e-01,  7.90873245e-01],
        [-4.59183848e-02,  1.75350060e-01],
        [-1.17394633e-02,  2.40275011e-01],
        [-1.08707954e+00,  2.63496049e-02],
        [-1.05788463e-01, -4.92294537e-01],
        [ 9.74950283e-01, -3.36332525e-01],
        [-1.01244822e+00,  3.76221255e-01],
        [-5.49104360e-01, -3.97427561e-01],
        [-4.08393323e-01,  2.53062628e-01],
        [ 8.96750148e-01, -1.94913555e-01],
        [ 7.98338038e-01, -1.57364534e-01],
        [-9.61692118e-01,  2.93570222e-01],
        [-5.99689767e-01, -3.86411653e-02],
        [ 1.00392257e+00, -4.31737267e-01],
        [-5.24247107e-01,  1.06838369e+00],
        [ 3.45739006e-01,  1.09184590e+00],
        [-5.07002799e-01,  8.886